name: Travbladet
favicon: null
layout_spectrum: 0.00417
typography_spectrum: 0.55306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6336525077931583
  lightness: 0.8689006257336587
  saturation: 0.625
  rhythmicContrast: 0.036850858479738235
purpose: []
